Feature/issue9
yinmyatthwe/inten-yinmyatthwe pull request #26
Opened 2024-03-06 04:17 UTC by yinmyatthwe

## Checklist for Developer
- [x] 最新のdevelopブランチをPullした。Pulled the latest develop branch.
  - できない理由 Reason not to do: 
- [x] Pull RequestをIssueに紐付けた。Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## 📝 そのほかの関連するIssue / Related issues other than connected one

- #9 
- #0

## ⛏ 変更内容 / Details of Changes

- matDialogを使って削除時にダイアログに確認しました。
- xxx

## 📸 スクリーンショット / Screenshots

<img width="1532" alt="スクリーンショット 2024-03-06 13 14 05" src="https://github.com/yinmyatthwe/inten-yinmyatthwe/assets/38120061/0441638f-d049-4671-b31a-de5a8fc94745">

## レビューするポイント (Points for review):

 - 
 -

2024-03-06 05:13 UTC, nannulwin commented
@yinmyatthwe マージ先mainになっていますよ。

2024-03-06 05:15 UTC, yinmyatthwe commented
@nannulwin マージ先交換しました。

2024-03-06 05:50 UTC, nannulwin requested changes

2024-03-06 05:50 UTC, nannulwin commented on intern-book-app/src/app/components/confirm-dialog/confirm-dialog.component.ts
> +  deleteBook(book:any){
動作的には問題ないんですが、deleteBook関数はこのcomponentではなくbookinformationコンポネートで書いた方がいいかなあと思います。dailogのafterClosed関数があるのでそれを使って「はい」を選択したか「いいえを」選択したか判断してdeleteBookを呼ぶようにしてみてください。

2024-03-06 05:50 UTC, nannulwin commented on intern-book-app/src/app/components/confirm-dialog/confirm-dialog.component.html
> +<h2 mat-dialog-title>削除しますか？</h2>
下記のように変更してもいいかなあと思います。
「削除しますか？」→「削除」

2024-03-06 05:50 UTC, nannulwin commented on intern-book-app/src/app/components/confirm-dialog/confirm-dialog.component.ts
> +
要らないnew lineの削除お願い致します。

2024-03-06 05:50 UTC, nannulwin commented on intern-book-app/src/app/components/confirm-dialog/confirm-dialog.component.ts
> +
ここのnew lineも削除お願い致します

2024-03-06 05:51 UTC, nannulwin commented
@yinmyatthwe 
screenshotの方の文言が違うかなあと思いますので修正終わった後にscreenshot置き換えもしてください〜

2024-03-07 00:16 UTC, yinmyatthwe commented
@nannulwin 全部更新しました。確認おねがいします。

2024-03-07 04:53 UTC, nannulwin approved these changes

2024-03-07 04:53 UTC, merged